pipelines:
  default:
    - step:
        name: Validation
        image: ubuntu:bionic
        script:
          - apt-get update -q
          - apt-get install -y --no-install-recommends python3-pip python3-setuptools
          - pip3 install cantools xmlschema
          - pip3 install matplotlib
          - cantools dump as_pacmod*.dbc
          - python3 tests/xml_validation.py
