pipelines:
  default:
    - step:
        name: Validation
        image: ubuntu:bionic
        script:
          - apt-get update -q
          - apt-get install -y --no-install-recommends python3-pip python3-setuptools python3-pil python3-wheel
          - pip3 install pillow wheel cantools xmlschema matplotlib
          - cantools dump as_pacmod*.dbc
          - python3 tests/xml_validation.py
  tags:
    '*':
      - step:
          name: DBC Release
          script:
          - mv as_pacmod.dbc as_pacmod_$BITBUCKET_TAG.dbc
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"as_pacmod_$BITBUCKET_TAG.dbc"