version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            pip install --user cantools
      - run:
          name: Validate DBC
          command: |
            /home/circleci/.local/bin/cantools dump as_pacmod*.dbc
