version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            pip install --user cantools xmlschema
            pip install --user matplotlib
      - run:
          name: Validate DBC
          command: |
            /home/circleci/.local/bin/cantools dump as_pacmod*.dbc
      - run:
          name: Validate XSD and XML
          command: |
            python tests/xml_validation.py
